=== fradicus/Shellhacks-2026/schemas/route.schema.json
{
  "$id": "https://gridbridge.local/schemas/route.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "$defs": {
    "point": {
      "additionalProperties": false,
      "properties": {
        "lat": {"maximum": 90, "minimum": -90, "type": "number"},
        "lon": {"maximum": 180, "minimum": -180, "type": "number"}
      },
      "required": ["lat", "lon"],
      "type": "object"
    },
    "nullable_point": {
      "oneOf": [{"$ref": "#/$defs/point"}, {"type": "null"}]
    }
  },
  "properties": {
    "_id": {"description": "match _id of the pair (sorted project keys joined by __)", "type": "string"},
    "a": {"type": "string"},
    "b": {"type": "string"},
    "origin": {"$ref": "#/$defs/point", "description": "Center of a when the route was computed"},
    "destination": {"$ref": "#/$defs/point", "description": "Center of b when the route was computed"},
    "status": {"enum": ["ok", "no_route"]},
    "distance_m": {"minimum": 0, "type": ["number", "null"]},
    "drive_mi": {"description": "Unrounded driving miles between the road points nearest each center", "minimum": 0, "type": ["number", "null"]},
    "duration_s": {"minimum": 0, "type": ["integer", "null"]},
    "polyline": {"description": "Encoded polyline, precision 5", "type": ["string", "null"]},
    "start": {"$ref": "#/$defs/nullable_point"},
    "end": {"$ref": "#/$defs/nullable_point"},
    "snap_m": {
      "description": "Meters from each center to the road point the router snapped it to",
      "oneOf": [
        {"items": {"minimum": 0, "type": "number"}, "maxItems": 2, "minItems": 2, "type": "array"},
        {"type": "null"}
      ]
    },
    "provider": {"type": "string"},
    "travel_mode": {"const": "DRIVE"},
    "routing_preference": {"type": "string"},
    "data_source": {"type": "string"},
    "computed_at": {"format": "date-time", "type": "string"}
  },
  "required": ["_id", "a", "b", "origin", "destination", "status", "distance_m", "drive_mi", "duration_s", "polyline",
               "start", "end", "snap_m", "provider", "travel_mode", "routing_preference", "data_source", "computed_at"],
  "if": {"properties": {"status": {"const": "ok"}}},
  "then": {"properties": {"drive_mi": {"type": "number"}, "distance_m": {"type": "number"}}},
  "title": "A stored driving route between two project centers (C46 drive rule)",
  "type": "object"
}

=== fradicus/Shellhacks-2026/data/routes/routes.json
[
  {
    "_id": "DESC:06367 D - G__GPC:20066",
    "a": "DESC:06367 D - G",
    "b": "GPC:20066",
    "computed_at": "2026-09-27T03:43:42Z",
    "data_source": "OpenStreetMap contributors (ODbL)",
    "destination": {
      "lat": 32.05402935,
      "lon": -81.09642410000001
    },
    "distance_m": 41112.2,
    "drive_mi": 25.54593672949972,
    "duration_s": 2682,
    "end": {
      "lat": 32.05403,
      "lon": -81.096429
    },
    "origin": {
      "lat": 32.3606993,
      "lon": -81.1241523
    },
    "polyline": "}lodEvbcnNnABrABjDDD@dLNpGHxEHh@@r@?p@Al@Cx@IbAMd@MHARE|Bi@vVcGlCo@|Cs@XGz@K|AKbAEt@?j@@fSv@lFVpFZdFZ@O`@gFRkCX{DFy@^iFPqCN}B@It@gLF_AToCRoCHq@nB_XvCw_@v@mJl@mIVaCTuBn@qFd@{Cf@mDvBcP@ShEWlHi@rPgAF?tCS@?xGc@lJm@jOcAdAIfF]V?LAnCSTAz@E~@Gf@ED?j@ErCQpBOTAfBM|@GbAI`BMHARA`@CJA`AG^Ch@ERAVCtAIRClBKNAbBMzBOp@ElAKf@ChCO`AGtDWxF[VCfCO~CSlE[rDUpDULAnCSrCSrAI`BKlIm@dAI`EYPCjCQhAKTAJCH?jF[bCMjBK\\CtAKbAGzHc@~AS`DSpAGb@EnCSxAUTGxA]FA`CiABAz@m@vAaALM`@WnA_AbBwAfAm@pBy@FADCp@Qp@Sn@KNGNMJOv@Gp@E`@CTCp@ElAK^Ef@CzAKz@IRAn@Ed@CNA`@Cx@GPAf@CJAvAIXCH?VCNAF?t@GPALA@?NAVAr@ERAVCRAH?hBI^CtBO`BONA~BMvBOlDU|AM\\EjBO`BK|@Gr@ERAj@EZC@?FAp@EJAj@GLA@?p@E~@Ir@GJA`DQ~AMzFc@lCShGg@`N_ArE[~Fe@xGc@|Fe@rCSzCUtAKxCSz@GbCOhOgAtJs@fBMxBQlDW~AKr@GhF_@dDWxFc@jFa@~BQbBMdAItDYn@En@GxHi@nCUdBMh@Ef^mCbCSjPmAnE]vGe@~Ea@hBM`Gc@LAxKw@rFe@bEYf@Ej@E\\C`BM`BMlBOpAKj@EdAI|CUtGe@J?\\CZC|@Cz@ExDC`BBT@tADZ@P@zBPN@`@Dz@JlAN\\Dz@Nh@JnCb@hARjItAtA^JBnBX~I|BjGxAlG|AbGnA`HjA|@N~AXtB\\hG~@`Ht@XBtBVhN~ArJnAf@H|F~@xCd@nI`B`CVbB@NCfAIdA[RGrBeAVM~BuAhBcA~@m@ZSPMl@a@n@]vCuBdDyCdBcBTUr@q@tEkE`GoFf@g@DC`AaAvBqBZ[fBaBhAeAzBwBJIjGaGVWdDyCrJeJ~BmB`Au@dCgBpDqCn@e@`BuApE_Et@u@xAsA|EmFtDaEbGyG~A{AzAqA|@g@vB}AbE{BnB{@bCiAbCcAZOvBk@bGsAjEk@~PkBnRoBxEe@hFSdEAjDHjDTxFt@tE~@jF|AfHvC~FlDpCtBzApAzExErLdOhfAjsAr`@tf@pDdEdElE`CtCl@t@LNlEdG~@tAjArAZZnBnB|@x@f[xW`KdHdEnCtAz@b@PrAn@RJxDjB~@b@z@d@nGtEr@l@rdAfx@~BnBt@p@|@`AdAz@d@f@h@j@V^Rd@Jf@Fn@?p@Gf@IZOZMTSRSLSHSFWD[?YAQCSIOIOMIIKOOYKWMc@Ga@Gi@?a@@k@B]D]Ja@HWJWHQr@gAbBeCfAgBz@yALS|@{Ap@gAHSL]\\{BHa@V{ADUBQF[V_BF[?Ah@aD|@iF@CBMJBx@TlBf@bAZPDf@Lb@Jl@Pl@N|@VD?X?f@NRFp@R^Jf@Nf@L~Ad@NDj@P@@B?j@NTFB@tA^F@fAZfAZx@TfAZFBH@RFj@Nb@L\\Hj@NLDPDZHz@TfAXLDJDTFrA\\F@l@PPDB?RHNNd@LD@d@Lt@RPFbAXjAZlA\\jAZNFr@RzA^tA^XFXHD@RDND`AXl@PDBRFNDdCl@|Bl@xCr@|Ab@hBf@lBb@jA\\pA\\lAZ~@TD@JBXFBQBOf@{C?EBODQDULu@X_Bz@aFZeBXaB@I@KRsARgABGBSDSRmAb@oC?EBMBKr@sDF_@XeBF[T{A@EBMXgBDa@DYBURFd@LZHvBj@b@LvA\\r@R",
    "provider": "osrm:router.project-osrm.org",
    "routing_preference": "FASTEST",
    "snap_m": [
      213.7,
      0.5
    ],
    "start": {
      "lat": 32.360627,
      "lon": -81.121883
    },
    "status": "ok",
    "travel_mode": "DRIVE"
  },
  {
    "_id": "DESC:06367 D - G__GPC:20067",
    "a": "DESC:06367 D - G",
    "b": "GPC:20067",
    "computed_at": "2026-09-27T03:43:43Z",
    "data_source": "OpenStreetMap contributors (ODbL)",
    "destination": {
      "lat": 32.044757399999995,
      "lon": -81.0672826
    },
    "distance_m": 43262.7,
    "drive_mi": 26.882195478406107,
    "duration_s": 2903,
    "end": {
      "lat": 32.044759,
      "lon": -81.067282
    },
    "origin": {
      "lat": 32.3606993,
      "lon": -81.1241523
    },
    "polyline": "}lodEvbcnNnABrABjDDD@dLNpGHxEHh@@r@?p@Al@Cx@IbAMd@MHARE|Bi@vVcGlCo@|Cs@XGz@K|AKbAEt@?j@@fSv@lFVpFZdFZ@O`@gFRkCX{DFy@^iFPqCN}B@It@gLF_AToCRoCHq@nB_XvCw_@v@mJl@mIVaCTuBn@qFd@{Cf@mDvBcP@ShEWlHi@rPgAF?tCS@?xGc@lJm@jOcAdAIfF]V?LAnCSTAz@E~@Gf@ED?j@ErCQpBOTAfBM|@GbAI`BMHARA`@CJA`AG^Ch@ERAVCtAIRClBKNAbBMzBOp@ElAKf@ChCO`AGtDWxF[VCfCO~CSlE[rDUpDULAnCSrCSrAI`BKlIm@dAI`EYPCjCQhAKTAJCH?jF[bCMjBK\\CtAKbAGzHc@~AS`DSpAGb@EnCSxAUTGxA]FA`CiABAz@m@vAaALM`@WnA_AbBwAfAm@pBy@FADCp@Qp@Sn@KNGNMJOv@Gp@E`@CTCp@ElAK^Ef@CzAKz@IRAn@Ed@CNA`@Cx@GPAf@CJAvAIXCH?VCNAF?t@GPALA@?NAVAr@ERAVCRAH?hBI^CtBO`BONA~BMvBOlDU|AM\\EjBO`BK|@Gr@ERAj@EZC@?FAp@EJAj@GLA@?p@E~@Ir@GJA`DQ~AMzFc@lCShGg@`N_ArE[~Fe@xGc@|Fe@rCSzCUtAKxCSz@GbCOhOgAtJs@fBMxBQlDW~AKr@GhF_@dDWxFc@jFa@~BQbBMdAItDYn@En@GxHi@nCUdBMh@Ef^mCbCSjPmAnE]vGe@~Ea@hBM`Gc@LAxKw@rFe@bEYf@Ej@E\\C`BM`BMlBOpAKj@EdAI|CUtGe@J?\\CZC|@Cz@ExDC`BBT@tADZ@P@zBPN@`@Dz@JlAN\\Dz@Nh@JnCb@hARjItAtA^JBnBX~I|BjGxAlG|AbGnA`HjA|@N~AXtB\\hG~@`Ht@XBtBVhN~ArJnAf@H|F~@xCd@nI`B`CVbB@NCfAIdA[RGrBeAVM~BuAhBcA~@m@ZSPMl@a@n@]vCuBdDyCdBcBTUr@q@tEkE`GoFf@g@DC`AaAvBqBZ[fBaBhAeAzBwBJIjGaGVWdDyCrJeJ~BmB`Au@dCgBpDqCn@e@`BuApE_Et@u@xAsA|EmFtDaEbGyG~A{AzAqA|@g@vB}AbE{BnB{@bCiAbCcAZOvBk@bGsAjEk@~PkBnRoBxEe@hFSdEAjDHjDTxFt@tE~@jF|AfHvC~FlDpCtBzApAzExErLdOhfAjsAr`@tf@pDdEdElE`CtCl@t@LNlEdG~@tAjArAZZnBnB|@x@f[xW`KdHdEnCtAz@b@PrAn@RJxDjB~@b@z@d@nGtEr@l@rdAfx@~BnBt@p@|@`AdAz@d@f@h@j@V^Rd@Jf@Fn@?p@Gf@IZOZMTSRSLSHSFWD[?YAQCSIOIOMIIKOOYKWMc@Ga@Gi@?a@@k@B]D]Ja@HWJWHQr@gAbBeCfAgBz@yALS|@{Ap@gAHSL]\\{BHa@V{ADUBQF[V_BF[?Ah@aD|@iF@CBMFYBM?AFMPSPYP[Fe@BI?CDSBQf@{CDS@GFe@j@}CBSDSl@sD@EDSPFz@Vv@RLBf@NPDt@RHB~@Vr@RHBNDZHx@{Et@oEBMb@qCLw@D]F[p@{D?ABKh@}CF]VwARkA@EBQ@Gl@kD@GNy@ZmB@CD[FW\\uB@AVyAb@mCLo@?CDQBKFOFSHOBCNOTUJGNIf@Y~@i@RKNIf@YZQ`Ak@^STMDCn@]JEHEVMTK|@e@nAs@RKp@a@j@[d@[^UXSj@[PKv@c@j@[pAu@`Ai@p@a@hAo@f@WZQPKp@_@TONIZQt@c@\\SjB}@TONIPMJKHKBC\\c@`BwCJSRa@BERk@JWRaABUJs@@CLgAHo@TgBNgANiAVyBFa@JcAJy@D[b@gEBUFe@Dg@Hg@La@R]`@a@^ONERI^INC@?ZMLC^GjAU@Al@KXGnAUdCg@b@KXGHA\\Ir@OHAbBi@^Mb@O^QjB{@^Ob@Sd@SdAa@^KZMjDwAbBm@bBw@nD{AjCeAnAi@z@]\\OvAg@HELEPGR?\\EF@N?XDTFXJH@^JVFzA`@VHf@LnA`@fAZNDz@TdAZ^Jb@LfAXfCp@Ml@WlA",
    "provider": "osrm:router.project-osrm.org",
    "routing_preference": "FASTEST",
    "snap_m": [
      213.7,
      0.2
    ],
    "start": {
      "lat": 32.360627,
      "lon": -81.121883
    },
    "status": "ok",
    "travel_mode": "DRIVE"
  },
  {
    "_id": "DESC:06367 D - G__GPC:20277",
    "a": "DESC:06367 D - G",
    "b": "GPC:20277",
    "computed_at": "2026-09-27T03:43:44Z",
    "data_source": "OpenStreetMap contributors (ODbL)",
    "destination": {
      "lat": 32.3521162,
      "lon": -81.1751124
    },
    "distance_m": 53381.3,
    "drive_mi": 33.16960202417879,
    "duration_s": 3598,
    "end": {
      "lat": 32.350888,
      "lon": -81.173236
    },
    "origin": {
      "lat": 32.3606993,
      "lon": -81.1241523
    },
    "polyline": "}lodEvbcnNnABrABjDDD@dLNpGHxEHh@@r@?p@Al@Cx@IbAMd@MHARE|Bi@vVcGlCo@|Cs@XGz@K|AKbAEt@?j@@fSv@lFVpFZdFZ@O`@gFRkCX{DFy@^iFPqCN}B@It@gLF_AToCRoCHq@nB_XvCw_@v@mJl@mIVaCTuBn@qFd@{Cf@mDvBcP@ShEWlHi@rPgAF?tCS@?xGc@lJm@jOcAdAIfF]V?LAnCSTAz@E~@Gf@ED?j@ErCQpBOTAfBM|@GbAI`BMHARA`@CJA`AG^Ch@ERAVCtAIRClBKNAbBMzBOp@ElAKf@ChCO`AGtDWxF[VCfCO~CSlE[rDUpDULAnCSrCSrAI`BKlIm@dAI`EYPCjCQhAKTAJCH?jF[bCMjBK\\CtAKbAGzHc@~AS`DSpAGb@EnCSxAUTGxA]FA`CiABAz@m@vAaALM`@WnA_AbBwAfAm@pBy@FADCp@Qp@Sn@KNGNMJOv@Gp@E`@CTCp@ElAK^Ef@CzAKz@IRAn@Ed@CNA`@Cx@GPAf@CJAvAIXCH?VCNAF?t@GPALA@?NAVAr@ERAVCRAH?hBI^ClAVn@TZP^Xd@j@r@|@~@bAfAn@p@Nt@FdAEpAC~@Eb@@^Df@Pr@b@h@h@hAnA`CpChCzC`Az@rLjO~Yj_@BDxRtV`FpG`AnAbAvAdA~An@bAr@jAv@|Ap@nAn@xAj@tA|@`C|@rCj@lBd@pBf@zB\\jB^zBLt@NrARjBNxAHvANpCFpADlBB~B?jCCdC]lKOhGShHI`DC|A?`C@dBBbCDfBFpAHrAP`CH`ARpBVpB\\`C\\nBVnAz@vDn@~Br@zBXz@f@rAjAtCt@bBvAnC~@`B`A|A|@tAtHlL|EnHvElH`SzZrZfe@`LbQ|DjGnHdLtB~CxFtIzK|PrAtBtHlL|DlGtEvGrEjFnJxKfGjGfBzAnD|CzBrBtTfQnh@pa@`BpArVxRzVzR~D~CvHbGPLbAz@dEbDnJlHd@t@xEnEhAjAp@r@f@n@h@r@nAjBjA|Ab@h@HZDL@H?F@HALCHCHEHKHUT{Cz@]Jc@Jy@TsA`@i@NuA^IBg@NaDz@o@Pu@RcBd@UH_AVmA\\SDe@LQFQFWFaAVo@VqAd@uAj@aAZgAZ_Cn@iD|@kD`AyF~AcFvAgA\\I@k@PmBh@gAXgARmAJO@m@B{@Do@?O?YAu@EOAkAMG?qAWu@SWGaCy@]M_A[yAg@wDuAg@Qg@SwAc@cA]s@WqEsAMGmAa@iHuBo@UmA_@uCaAmC{@_A[q@WkEoAQGy@Yg@UmDeAg@Q{@YuDgA]KWIaAYsA[gAQiFk@wO}@iDQ_G]y@CeAIcAAg@@k@@mCNk@Fa@D_@FIBk@N}@PgCv@q@VsAj@sAt@yAdAEDSPa@\\QP[Vc@b@YZy@`AEDi@r@Yb@uA|BeAwAS[qAgB[w@i@_BOq@e@wBi@_Cs@cBsAmBoAkAyAw@aA]{@O]@MEq@Me@YGMKKMCM?MBCB_@Hq@NY@IFqACyBEwBEyCAaBAi@AyMuBcDi@uJiBwE{@yE}@wAYiCe@_Dk@]IyBa@iEw@uBa@kB]{Ck@gAUgDi@wFcAcAMwGy@_DHcDf@mIjBs@Pg@?iHZqM^aELqKZa@@s@@aDLy@BK@eABqETe@@]@Q@kBFgGRo@BcADoEN_@BI@yANeARE@_B^}Cx@iCp@C@wA\\gCp@sA^KB{Bj@{AZsATk@Fo@FO@[@m@D}AB}BEwJSuFOoAEmACoEKC?sISoFMqBG{CM[Ac@A_@?c@?m@Bi@Fi@Hc@Lc@NYJYNE@]Te@ZYRYVWVUXU\\S\\Ub@Sb@Sh@Wv@Y~@ITg@~A_@`Am@hAaAlAMDIAI@IBEFEHCJ?HQT_Av@qAp@aA^eD~AyJvEyBdAoB~@MFoCpAwAr@UJ{@d@eItDgAd@{Ad@eCh@aDb@mANcBT{ARmDd@o@LiALcH`AgCXA@E?A?oBVE?{C^yA\\k@VkAv@sEfEKJeCrBmGhFyD`DwAlA[ZOLSPy@v@uFvEmB`Bm@h@ED_BtA_CnBA@]Zi@b@{ChCkDvCA@k@TyAb@yBPmD?uFJqLFwEBC?oGB{@FcKl@a@DA@eFbAcFdAa@Jg@Xs@^s@f@g@l@GHSToElLK\\A@eDlJ]x@A@]v@aAhBs@|@s@p@m@n@k@j@WXGDIDI@G?G@G?C?CACAGEKMOUWa@S[S_@a@k@wAcDo@_BCEO]ACg@gAYs@Wq@mA{BCE}@cBEGAC}BgEACMU_@q@EKsBuD_AgBAAEKGISa@[m@_AgBa@w@q@oAgAuBACKSoA_C{FaLcAiB{@}A@C?Gq@qAEI_@u@]s@AAWi@??i@gACEuAoCQ_@ACgBmDo@qAaC{EUe@{AeDEGUe@eEuIwAeCMUEIaDsG}F{LaDkGAA{CaGCEqB}DaEmIUe@gSyb@`CgDj@s@n@q@j@g@l@c@n@a@x@c@RIf@Sh@QDC@?xA]nASxIoAx[gGlAQ~CWXCVCB?pAKl@GlAGtAAfEBnIC~IIlDEpCCjAA~FE@?xEE~BCrA?jA?n@@SaNCoBGmCO}@Ss@Ok@k@cAgFsE",
    "provider": "osrm:router.project-osrm.org",
    "routing_preference": "FASTEST",
    "snap_m": [
      213.7,
      223.0
    ],
    "start": {
      "lat": 32.360627,
      "lon": -81.121883
    },
    "status": "ok",
    "travel_mode": "DRIVE"
  },
  {
    "_id": "DESC:06367 D - G__GPC:20407",
    "a": "DESC:06367 D - G",
    "b": "GPC:20407",
    "computed_at": "2026-09-27T03:43:46Z",
    "data_source": "OpenStreetMap contributors (ODbL)",
    "destination": {
      "lat": 32.0226869,
      "lon": -81.0861807
    },
    "distance_m": 46171.0,
    "drive_mi": 28.689329316789944,
    "duration_s": 2984,
    "end": {
      "lat": 32.022232,
      "lon": -81.086348
    },
    "origin": {
      "lat": 32.3606993,
      "lon": -81.1241523
    },
